config/routes.rb
ReAdmin::Application.routes.draw do
  mount ApiApp, at: "/api"
  resources :companies
  resources :company_users
  devise_for :users, :controllers => {
    registrations: 'registrations'
  }
  mount Ckeditor::Engine => '/ckeditor'
  resources :real_estate_images

  resources :real_estates do
    member do
      post :upload_images
      get :destroy_image, :reload_images, :update_image_master
    end
  end

  root 'real_estates#index'

  get 'datatable/i18n' => 'datatable#i18n'

end

app/models/real_estate.rb
class RealEstate < ActiveRecord::Base
  TYPES = {apartment: 'Apartamento', house: 'Casa', ground: 'Terreno',
    farm: 'Fazenda', hostel: 'Pousada', horse_farm: 'Haras', shop: 'Loja',
    restaurant: 'Restaurante', comercial_room: 'Sala', sitio: 'Sítio'}
  has_paper_trail

  has_many :goal_real_estates
  has_many :goals, through: :goal_real_estates
  has_many :real_estate_images, order: 'master desc'
  belongs_to :real_estate_image
  belongs_to :company

  validates :title, :short_description, :real_estate_type, :company, presence: true

  usar_como_dinheiro :selling_price, :comission_price, :sold_price, :terrain_area, :build_area

  def last_modification_by
    User.find(self.versions.last.whodunnit).try(:name)
  end

  def address_country
    'Brasil'
  end

  def real_estate_type_full_text
    RealEstate::TYPES[self.real_estate_type.to_sym]
  end

  def to_api(simple = false)
    response = {
      id: self.id,
      title: self.title,
      short_description: self.short_description,
      type: self.real_estate_type_full_text,
      sold_at: self.sold_at.to_s,
      sold_price: self.sold_price.to_s,
      selling_price: self.selling_price.to_s,
      comission_price: self.comission_price.to_s,
      image: self.real_estate_image ? self.real_estate_image.image.url : '',
      updated_at: self.updated_at.to_s,
      created_at: self.created_at.to_s,
      last_modification_by: self.last_modification_by
    }
    unless simple
      response = response.merge({
        address: {
          zipcode: self.address_zipcode.to_s,
          address: self.address.to_s,
          number: self.address_number.to_s,
          complement: self.address_complement.to_s,
          neighborhood: self.address_neighborhood.to_s,
          reference: self.address_reference.to_s,
          region: self.address_region.to_s,
          city: self.address_city.to_s,
          state: self.address_state.to_s,
          country: self.address_country.to_s
        },
        specifications: {
          gated: self.gated.to_s,
          rooms: self.rooms.to_s,
          bathrooms: self.bathrooms.to_s,
          terrain_area: self.terrain_area.to_s,
          build_area: self.build_area.to_s,
          fireplace: self.fireplace.to_s,
          pool: self.pool.to_s,
          bbq_area: self.bbq_area.to_s,
          kennel: self.kennel.to_s,
          dependencies: self.dependencies.to_s,
          homemade_house: self.homemade_house.to_s,
          turkish_bath: self.turkish_bath.to_s,
          game_room: self.game_room.to_s,
        },
        owner: {
          name: self.owner_name.to_s,
          phone: self.owner_phone.to_s,
          mobile_phone: self.owner_mobile_phone.to_s,
        },
        agent: {
          name: self.owner_agent_name.to_s,
          phone: self.owner_agent_phone.to_s,
          mobile_phone: self.owner_agent_mobile_phone.to_s,
        },
        images: images_url
      })
    end
    response
  end

  def images_url
    self.real_estate_images.collect{|t| t.image.url}
  end
end

app/controllers/real_estates_controller.rb
class RealEstatesController < ApplicationController
  add_breadcrumb :index, :real_estates_path
  before_action :set_real_estate, only: [:show, :edit, :update, :destroy,
    :upload_images, :destroy_image, :reload_images, :update_image_master]
  skip_before_filter :verify_authenticity_token, :only => [:upload_images]

  # GET /real_estates
  # GET /real_estates.json
  def index
    @real_estates = []
    if current_user.master?
      @real_estates = current_user.company.all_real_estates
    else
      @real_estates = current_user.company.real_estates
    end
  end

  # GET /real_estates/1
  # GET /real_estates/1.json
  def show
    add_breadcrumb :show, real_estate_path(@real_estate)
  end

  # GET /real_estates/new
  def new
    add_breadcrumb :new, new_real_estate_path
    @real_estate = RealEstate.new
  end

  # GET /real_estates/1/edit
  def edit
    add_breadcrumb :edit, edit_real_estate_path(@real_estate)
  end

  # POST /real_estates
  # POST /real_estates.json
  def create
    add_breadcrumb :new, new_real_estate_path
    @real_estate = RealEstate.new(real_estate_params)

    respond_to do |format|
      if @real_estate.save
        format.html { redirect_to edit_real_estate_path(@real_estate), notice: 'Informações salvas com sucesso.' }
        format.json { render action: 'show', status: :created, location: @real_estate }
      else
        format.html { render action: 'new' }
        format.json { render json: @real_estate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /real_estates/1
  # PATCH/PUT /real_estates/1.json
  def update
    add_breadcrumb :edit, edit_real_estate_path(@real_estate)
    respond_to do |format|
      if @real_estate.update(real_estate_params)
        format.html { redirect_to @real_estate, notice: 'Informações salvas com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @real_estate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /real_estates/1
  # DELETE /real_estates/1.json
  def destroy
    @real_estate.destroy
    respond_to do |format|
      format.html { redirect_to real_estates_url }
      format.json { head :no_content }
    end
  end

  def reload_images
    respond_to do |format|
      format.js
    end
  end

  def update_image_master
    real_estate_image = @real_estate.real_estate_images.find(params[:real_estate_image_id])
    if real_estate_image
      @real_estate.real_estate_images.update_all(master: false)
      real_estate_image.master = true
      real_estate_image.save
      respond_to do |format|
        format.js { render action: 'reload_images'}
      end
    else
      render nothing: true
    end
  end

  def upload_images
    real_estate_image = @real_estate.real_estate_images.build(image: params[:file])
    real_estate_image.save!
    render nothing: true
  end

  def destroy_image
    real_estate_image = @real_estate.real_estate_images.find(params[:real_estate_image_id])
    respond_to do |format|
      if real_estate_image && real_estate_image.destroy
        format.js { render action: 'reload_images'}
      else
        format.js { render nothing: true}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_real_estate
      @real_estate = nil
      if current_user.master?
        @real_estate = current_user.company.all_real_estates.find(params[:id])
      else
        @real_estate = current_user.company.real_estates.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def real_estate_params
      _params = params.require(:real_estate).permit(:real_estate_type, :title,
        :short_description, :description, :address_zipcode, :address, :address_number,
        :address_complement, :address_neighborhood, :address_reference,
        :address_region, :address_city, :address_state, :address_country,
        :selling_price, :comission_price, :sold, :active, :owner_name,
        :owner_phone, :owner_mobile_phone, :owner_agent_name,
        :owner_agent_phone, :owner_agent_mobile_phone, :gated, :rooms,
        :bathrooms, :terrain_area, :build_area, :fireplace, :pool, :bbq_area,
        :kennel, :dependencies, :homemade_house, :turkish_bath, :game_room,
        :sold_price, :sold_at, real_estate_specifications_attributes:[
          :value, :specification, :specification_id, :id, :_destroy])
      _params.merge({company: current_user.company, goal_ids: params[:real_estate][:goal_ids]})
    end
end

app/helpers/real_estates_helper.rb
# encoding: utf-8
module RealEstatesHelper
  def real_estate_type_options
    RealEstate::TYPES.collect{|k,v| [v,k]}
  end

  def css_class_of_master(real_estate_image)
    "master" if real_estate_image.master
  end


  def state_options
    %w(AC AL AP AM BA CE DF ES GO MA MT MS MG PA PB PR PE PI RJ RN RS RO RR SC SP SE TO)
  end

  def image_dimenssions(file_path)
    geo = Paperclip::Geometry.from_file(file_path)
    "#{geo.width.round}x#{geo.height.round}"
  end
end

app/views/real_estates/_form.html.erb
<%= simple_nested_form_for(@real_estate, defaults: { input_html: { class: 'span10' } }, html: {class: 'form-horizontal'}) do |f| %>
<div class="real_estate_tabs">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">Resumo do imóvel</a></li>
    <li><a href="#tab2" data-toggle="tab">Características</a></li>
    <li><a href="#tab3" data-toggle="tab">Proprietário</a></li>
    <% unless @real_estate.new_record? %>
    <li>
      <a href="#tab4" data-toggle="tab" id="tabImages"
      data-ajax-source="<%= reload_images_real_estate_path(@real_estate, format: :js) %>">
      Imagens (<%=@real_estate.real_estate_images.count %>)
      </a>
    </li>
    <% end -%>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
      <%= render partial: 'resume', locals: {f: f} %>
    </div>
    <div class="tab-pane" id="tab2">
      <%= render partial: 'specifications', locals: {f: f} %>
    </div>
    <div class="tab-pane" id="tab3">
      <%= render partial: 'owner', locals: {f: f} %>
    </div>
    <% unless @real_estate.new_record? %>
    <div class="tab-pane" id="tab4">
    </div>
    <% end -%>
  </div>
</div>

<fieldset>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
    <%= link_to t('back_list'), {action: :index}, class: 'btn' %>
  </div>
</fieldset>
<% end %>

app/views/real_estates/_images.html.erb
<%= render partial: "images_grid" %>
<%= render partial: "images_upload" %>

app/views/real_estates/_images_grid.html.erb
<div class="row-fluid">
  <div class="span12">
    <div id="large_grid" class="wmk_grid">
      <ul>
        <% @real_estate.real_estate_images.each do |real_estate_image| %>
        <li class="thumbnail image_<%=real_estate_image.id%> <%=css_class_of_master(real_estate_image) %>">
          <a href="<%=real_estate_image.image.url(:big) %>" title="<%=real_estate_image.image_file_name %>">
            <img src="<%= real_estate_image.image.url(:medium) %>" alt="" />
          </a>
          <p>
            <%= link_to '<i class="icon-trash"></i>'.html_safe,
              destroy_image_real_estate_path(@real_estate,real_estate_image_id: real_estate_image.id),
              remote: true,
              title: "Apagar" %>
            
              <% unless real_estate_image.master %>
                <%= link_to 'Tornar principal',
                update_image_master_real_estate_path(@real_estate,real_estate_image_id: real_estate_image.id),
                remote: true,
                class: 'btn btn-primary btn-mini' %>
              <% else %>
              <%= link_to 'Imagem principal',
                'javascript:;',
                class: 'btn btn-primary btn-mini disabled btn-success' %>
              <% end -%>
            <br />
            <span>
              
              Nome: <%=content_tag(:u, truncate(real_estate_image.image_file_name), title: real_estate_image.image_file_name) %><br />
              Dimensões: <u><%=image_dimenssions(real_estate_image.image.path) %></u>
            </span>

          </p>
        </li>
        <% end -%>
      </ul>
    </div>
  </div>
</div>

app/views/real_estates/_images_upload.html.erb
<div class="row-fluid">
  <div class="span12">
    <h3 class="heading">Envio de imagens</h3>
    <div id="multi_upload" class="gebo-upload">
      <p>You browser doesn't have Flash, Silverlight or HTML5 support.</p>
    </div>
  </div>
</div>

app/views/real_estates/_owner.html.erb
<div class="row-fluid">
  <div class="span6">
    <%= f.input :owner_name %>
  </div>
</div>
<div class="row-fluid">
  <div class="span6">
    <%= f.input :owner_phone %>
  </div>
  <div class="span6">
    <%= f.input :owner_mobile_phone %>
  </div>
</div>
<h3 class="heading">Representante</h3>
<div class="row-fluid">
  <div class="span6">
    <%= f.input :owner_agent_name %>
  </div>
</div>
<div class="row-fluid">
  <div class="span6">
    <%= f.input :owner_agent_phone %>
  </div>
  <div class="span6">
    <%= f.input :owner_agent_mobile_phone %>
  </div>
</div>

app/views/real_estates/_resume.html.erb
<div class="row-fluid">
  <div class="span6">
    <%= f.input :title%>
  </div>
  <div class="span6">
    <%= f.input :real_estate_type, collection: real_estate_type_options, include_blank: false %>
  </div>
</div>
<div class="row-fluid">
  <div class="span6">
    <%= f.input :short_description %>
  </div>
  <div class="span6">
    <%= f.input :description %>
  </div>
</div>
<div class="row-fluid">
  <div class="span6">
    <div class="ui_slider1"></div>
    <input type="hidden" name="ui_slider_default_val" id="ui_slider_default_val"/>
    <%= f.input :selling_price, :wrapper => :prepend do %>
      <span class="add-on"><%= t('number.currency.format.unit')%></span><%= f.text_field :selling_price, class: :currency, value: f.object.selling_price.to_s %>
    <% end %>
  </div>
  <div class="span6">
    <%= f.input :comission_price, :wrapper => :prepend do %>
      <span class="add-on"><%= t('number.currency.format.unit')%></span><%= f.text_field :comission_price, class: :currency, value: f.object.comission_price.to_s %>
    <% end %>
  </div>
</div>
<div class="row-fluid">
  <div class="span6">
    <%= f.input :sold, input_html: {class: nil} %>
  </div>
  <div class="span6">
    <%= f.input :active, input_html: {class: nil} %>
  </div>
</div>
<div class="row-fluid sold_info">
  <div class="span6">
    <%= f.input :sold_price, :wrapper => :prepend do %>
      <span class="add-on"><%= t('number.currency.format.unit')%></span><%= f.text_field :sold_price, class: :currency, value: f.object.sold_price.to_s %>
    <% end %>
  </div>
  <div class="span6">
    <%= f.input :sold_at, :wrapper => :prepend do %>
      <span class="add-on"><i class="splashy-calendar_day_up"></i></span><%= f.text_field :sold_at, value: f.object.sold_at.try(:strftime, "%d/%m/%Y"), class: 'span7' %>
    <% end -%>
  </div>
</div>
<%= f.association :goals, collection: Goal.order('name ASC'), input_html: {class: 'multiselect'} %>

<h3 class="heading">Localidade</h3>
<div class="row-fluid">
  <div class="span6">
    <%= f.input :address_zipcode %>
  </div>
  <div class="span6">
    <%= f.input :address %>
  </div>
</div>

<div class="row-fluid">
  <div class="span6">
    <%= f.input :address_number %>
  </div>
  <div class="span6">
    <%= f.input :address_complement %>
  </div>
</div>

<div class="row-fluid">
  <div class="span6">
    <%= f.input :address_neighborhood %>
  </div>
  <div class="span6">
    <%= f.input :address_reference %>
  </div>
</div>

<div class="row-fluid">
  <div class="span6">
    <%= f.input :address_region %>
  </div>
  <div class="span6">
    <%= f.input :address_city %>
  </div>
</div>

<div class="row-fluid">
  <div class="span6">
    <%= f.input :address_state, collection: state_options %>
  </div>
  <div class="span6">
    <%= f.input :address_country, as: :string, input_html: {value: 'Brasil', disabled: :disabled} %>
  </div>
</div>

app/views/real_estates/_specifications.html.erb
<div class="row-fluid">
  <div class="span6">
    <%= f.input :rooms, input_html: {placeholder: 'Ex.: 2 quartos de fundo, 1 suíte, 1 quarto de hóspede'} %>
  </div>
  <div class="span6">
    <%= f.input :bathrooms, input_html: {placeholder: 'Ex.: 3 banheiros, 1 suíte, 2 lavabos'} %>
  </div>
</div>
<div class="row-fluid">
  <div class="span6">
    <%= f.input :terrain_area, :wrapper => :prepend do %>
      <span class="add-on">m²</span><%= f.text_field :terrain_area, class: 'currency', value: f.object.terrain_area.to_s %>
    <% end %>
  </div>
  <div class="span6">
    <%= f.input :build_area, :wrapper => :prepend do %>
      <span class="add-on">m²</span><%= f.text_field :build_area, class: 'currency', value: f.object.build_area.to_s %>
    <% end %>
  </div>
</div>
<div class="row-fluid">
  <div class="span6">
    <%= f.input :fireplace, input_html: {class: nil} %>
    <%= f.input :pool, input_html: {class: nil} %>
    <%= f.input :gated, input_html: {class: nil} %>
    <%= f.input :bbq_area, input_html: {class: nil} %>
    <%= f.input :kennel, input_html: {class: nil} %>
    <%= f.input :dependencies, input_html: {class: nil} %>
    <%= f.input :homemade_house, input_html: {class: nil} %>
    <%= f.input :turkish_bath, input_html: {class: nil} %>
    <%= f.input :game_room, input_html: {class: nil} %>
  </div>
</div>

app/views/real_estates/edit.html.erb
<h2 class="heading">
  <%=t('breadcrumbs.real_estates.edit')%>
  <div class="pull-right">
    <div class="btn-group">
      <%= link_to t('resume_mode'), url_for(action: :show, id: params[:id]), class: 'btn btn-mini' %>
      <%= link_to t('back_list'), url_for(action: :index), class: 'btn btn-mini btn-inverse' %>
    </div>
  </div>
</h2>

<%= render 'form' %>

app/views/real_estates/index.html.erb
<h2 class="heading"><%=t('breadcrumbs.real_estates.index')%>
<div class="pull-right"><%= link_to t('new'), new_real_estate_path, class: 'btn btn-mini btn-inverse' %></div>
</h2>
<div class="row-fluid">
  <div class="span12">
    <table class="table table-striped table-bordered table-condensed dTableR" id="realEstateTableList">
      <thead>
        <tr>
          <th>ID</th>
          <th><%= RealEstate.human_attribute_name(:title)%></th>
          <th><%= RealEstate.human_attribute_name(:short_description)%></th>
          <th><%= RealEstate.human_attribute_name(:address_region) %></th>
          <th><%= RealEstate.human_attribute_name(:address_city) %></th>
          <th width="300"></th>
        </tr>
      </thead>

      <tbody>
      </tbody>
    </table>
  </div>
</div>
<script type="text/javascript">
  var realEstateTableData = []
  <% @real_estates.each do |real_estate| %>
    realEstateTableData.push(["<%=real_estate.id%>",
      "<%=j real_estate.title%>",
      "<%=j real_estate.short_description%>",
      "<%=j real_estate.address_region%>",
      "<%=j real_estate.address_city%>",
      "<%=j (link_to(t('show'), real_estate, class: "btn btn-mini").html_safe + ' ' +
            link_to(t('edit'), edit_real_estate_path(real_estate), class: "btn btn-mini").html_safe + ' ' +
            link_to(t('delete'), real_estate, method: :delete, data: { confirm: t('confirm') }, class: "btn btn-mini btn-danger").html_safe) %>"
      ])
  <% end %>
  $(document).ready(function(){
    $('#realEstateTableList').dataTable({
      "sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
      "sPaginationType": "bootstrap_alt",
      "oLanguage": {
        "sUrl": "/datatable/i18n"
      },
      "aaSorting": [[ 0, "desc" ]],
      "aoColumnDefs": [{ "bSortable": false, "aTargets": [ 5 ] }],
      "aaData": realEstateTableData,
      "aoColumns": [
        { "sClass": "center" },
        { },
        { },
        { },
        { },
        { "sClass": "center" }
      ]
    })
  });
</script>

app/views/real_estates/new.html.erb
<h2 class="heading">
  <%=t('breadcrumbs.real_estates.new')%>
  <div class="pull-right"><%= link_to t('back_list'), url_for(action: :index), class: 'btn btn-mini btn-inverse' %></div>
</h2>

<%= render 'form' %>

app/views/real_estates/reload_images.js.erb
$('#tab4').html("<%=j render partial: 'images' %>")

$(document).ready(function(){

  $('#tabImages').text('Imagens (<%=@real_estate.real_estate_images.count%>)')
  $("#multi_upload").pluploadQueue({
    // General settings
    runtimes : 'html5,flash,silverlight',
    url : '<%=upload_images_real_estate_path(@real_estate)%>',
    max_file_size : '10mb',
    chunk_size : '1mb',
    unique_names : true,
    browse_button : 'pickfiles',

    // Specify what files to browse for
    filters : [
        {title : "Arquivos de imagem", extensions : "jpg,gif,png"},
        {title : "Arquivos ZIP", extensions : "zip"}
    ],

    // Flash settings
    flash_swf_url : '/plupload/js/plupload.flash.swf',

    // Silverlight settings
    silverlight_xap_url : '/plupload/js/plupload.silverlight.xap'
  });
  var uploader = $('#multi_upload').pluploadQueue(); 
  uploader.bind('FileUploaded', function(up, file, res) {
      if(this.total.queued == 0){
        $.get('<%= reload_images_real_estate_path(@real_estate, format: :js) %>')
      }
  });
  gebo_gal_grid.init();
  gebo_gal_grid.large();
})