config/routes.rb
ReAdmin::Application.routes.draw do
  mount ApiApp, at: "/api"
  resources :companies
  resources :company_users
  devise_for :users, :controllers => {
    registrations: 'registrations'
  }
  mount Ckeditor::Engine => '/ckeditor'
  resources :real_estate_images

  resources :real_estates do
    member do
      post :upload_images
      get :destroy_image, :reload_images, :update_image_master
    end
  end

  root 'real_estates#index'

  get 'datatable/i18n' => 'datatable#i18n'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ForAll Imobiliária</title>

    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>


    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=PT+Sans" />


    <!--[if lte IE 8]>
    <link rel="stylesheet" href="css/ie.css" />
    <script src="js/ie/html5.js"></script>
    <script src="js/ie/respond.min.js"></script>
    <![endif]-->
    <script>
      //* hide all elements & show preloader
      document.documentElement.className += 'js';
    </script>
  </head>
  <body>
    <div id="loading_layer" style="display:none"><%= image_tag "ajax_loader.gif" %></div>

    <div id="maincontainer" class="clearfix">
      <!-- header -->
      <header>
        <div class="navbar navbar-fixed-top">
          <div class="navbar-inner">
            <div class="container-fluid">
              <a class="brand" href="<%=root_path%>"><i class="icon-home icon-white"></i> <%=current_user.company.name%></a>
              <ul class="nav user_menu pull-right">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Usuário <u><%= current_user.name %></u> <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a data-toggle="modal" data-target="#editRegistrationModal" href="<%= edit_user_registration_path %>">Meus dados</a></li>
                    <li class="divider"></li>
                    <li><%=link_to t('sign_out'), destroy_user_session_path %></li>
                  </ul>
                </li>
              </ul>
              <a data-target=".nav-collapse" data-toggle="collapse" class="btn_menu">
                <span class="icon-align-justify icon-white"></span>
              </a>
              <nav>
                <div class="nav-collapse">
                  <ul class="nav">
                    <li class="dropdown">
                      <a data-toggle="dropdown" class="dropdown-toggle" href="#"><i class="icon-home icon-white"></i> Imóveis <b class="caret"></b></a>
                      <ul class="dropdown-menu">
                        <li><a href="<%=new_real_estate_path%>">Novo imóvel</a></li>
                        <li><a href="<%=real_estates_path%>">Lista de imóveis</a></li>
                      </ul>
                    </li>
                    <% if current_user.master? || current_user.sys_admin? %>
                    <li class="dropdown">
                      <a data-toggle="dropdown" class="dropdown-toggle" href="#"><i class="icon-user icon-white"></i> Usuários <b class="caret"></b></a>
                      <ul class="dropdown-menu">
                        <li><a href="<%= new_company_user_path %>">Novo usuário</a></li>
                        <li><a href="<%= company_users_path %>">Lista de usuários</a></li>
                      </ul>
                    </li>
                    <li class="dropdown">
                      <a data-toggle="dropdown" class="dropdown-toggle" href="#"><i class="icon-edit icon-white"></i> Imobiliárias <b class="caret"></b></a>
                      <ul class="dropdown-menu">
                        <li><a href="<%= new_company_path %>">Nova imobiliária</a></li>
                        <li><a href="<%= companies_path %>">Lista de imobiliárias</a></li>
                      </ul>
                    </li>
                    <% end -%>
                  </ul>
                </div>
              </nav>
            </div>
          </div>
        </div>
      </header>

      <!-- main content -->
      <div id="contentwrapper">
        <div class="main_content">
          <%= bootstrap_flash %>
          <%= render_breadcrumbs %>
          <%=yield -%>
        </div>
      </div>
      <script type="text/javascript" src="/plupload/js/plupload.full.js"></script>
      <script type="text/javascript" src="/plupload/js/jquery.plupload.queue/jquery.plupload.queue.full.js"></script>
      <script>
      $(document).ready(function() {
        //* show all elements & remove preloader
        setTimeout('$("html").removeClass("js")',1000);
      });
      </script>
    </div>
    <div id="editRegistrationModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <%= render partial: "registrations/edit" %>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ForAll Imobiliária::Login</title>

    <%= stylesheet_link_tag    "devise", media: "all" %>
    <%= csrf_meta_tags %>


    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=PT+Sans" />


    <!--[if lte IE 8]>
    <link rel="stylesheet" href="css/ie.css" />
    <script src="js/ie/html5.js"></script>
    <script src="js/ie/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="login_page">
    <%= yield %>
    <%= javascript_include_tag "devise" %> 
    <script>
      $(document).ready(function(){
        $('#login_form').submit(function(){
          return true;
        })
        //* boxes animation
        form_wrapper = $('.login_box');
        $('.linkform a,.link_reg a').on('click',function(e){
          $('.alert-error').remove()
          var target    = $(this).attr('href'),
          target_height = $(target).actual('height');
          $(form_wrapper).css({'height': form_wrapper.height()}); 
          $(form_wrapper.find('form:visible')).fadeOut(400,function(){
            form_wrapper.stop().animate({height: target_height },500,function(){
              $(target).fadeIn(400);
              $('.links_btm .linkform').toggle();
              $(form_wrapper).css({
                'height'    : ''
              }); 
            });
          });
          e.preventDefault();
        });
      });
    </script>
  </body>
</html>